### ISSUE TITLE
/poem/exec/ZOPH_RNN_GPU_EXPAND: Permission denied

### ISSUE THREAD

**Issue by shaomai00** [shixing/poem#1]
when I called bash run_standalone.sh ,it says permission denied,I found that if I want to use this executable  ZOPH_RNN_GPU_EXPAND  the error will appear. 
what's more ,when I git clone the Topical_poetry it also has error:
Error downloading object: data/distance_all (8909800): Smudge error: Error downl oading data/distance_all (89098005141ed251798cce0f569ced0c5c90b266dd11799b0ed189 eafc03500b): batch response: This repository is over its data quota. Purchase mo re data packs to restore access.
please help!

**Comment by AIshutin** [comment]
I`ve this problem too. Have you found a solution?

**Comment by shaomai00** [comment]
yes,you must compile the executable by yourself, how to compile it can be found here: https://github.com/isi-nlp/Zoph_RNN/blob/master/README_XING.md
